<?php require 'common/begin.php' ?>

<!-- MAIN CONTENT -->
<div class="main-content">
    <div class="content-wrapper">
        <div class="page-section" id="about">
            <div class="row">
                <div class="user-form">
                    <form id="changepw-form" class="user-auth-form" novalidate="novalidate">
                        <input type="password" id="inputCurrentPassword" class="form-control" placeholder="Current Password" required>
                        <input type="password" id="inputNewPassword" class="form-control" placeholder="New Password" required>
                        <input type="password" id="inputConfirm" class="form-control" placeholder="Confirmation" required>
                        <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Change Password!</button>
                    </form><!-- /form -->
                    <br/>
                </div>
            </div>
            <?php require 'common/footer.php' ?>
        </div>
    </div>
</div>
<?php require 'common/end.php' ?>


