<?php require 'common/begin.php' ?>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="js/charts.js"></script>
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="fluid-container">
            <div class="content-wrapper">

                <div class="page-section" id="about">
                    <!--Div that will hold the line chart-->
                    <div id="linechart_material"></div>
                <div class="row">
                    This is charts page
                </div> <!-- #about -->
                </div>
                <?php require 'common/footer.php' ?>
            </div>
        </div>
    </div>
<?php require 'common/end.php' ?>
