<?php require 'common/begin.php' ?>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="js/charts.js"></script>
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="fluid-container">
            <div class="content-wrapper">

                <div class="page-section" id="about">
                    <!--Div that will hold the dashboard-->
                    <div id="air_dashboard_div">
                        <!--Divs that will hold each control and chart-->
                        <div id="air_category_div"></div>
                        <!--Div that will hold the line chart-->
                        <div id="air_chart_div"></div>
                        <div id="air_range_div"></div>
                    </div>
                    <div id="heart_dashboard_div">
                        <!--Divs that will hold each control and chart-->
                        <!--Div that will hold the line chart-->
                        <div id="heart_chart_div"></div>
                        <div id="heart_range_div"></div>
                    </div>
                <div class="row">
                </div> <!-- #about -->
                </div>
                <?php require 'common/footer.php' ?>
            </div>
        </div>
    </div>
<?php require 'common/end.php' ?>
