<?php require 'common/begin.php' ?>

    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="fluid-container">
            <div class="content-wrapper">

                <!-- ABOUT -->
                <div class="page-section" id="about">
                    <div class="page-section" id="projects">
                        <div class="row">
                            <div class="col-xs-12">
                                <h4 class="widget-title">Team Information</h4>
                                <!--<p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Maecenas et lorem molestie, maximus justo dignissim, cursus nisl. Nullam at ante quis ex pharetra pulvinar quis id dolor. Integer lorem odio, euismod ut sem sit amet, imperdiet condimentum diam.</p>-->
                            </div>
                        </div>
                        <div class="row projects-holder">
                            <div class="col-xs-12 col-md-4 col-sm-6">
                                <div class="project-item">
                                    <img src="img/developers/felix.png" alt="">
                                    <div class="project-hover">
                                        <div class="inside">
                                            <h5><a href="#">Mookeun Ji (Felix)</a></h5>
                                            <p>Sensor, and our TEAM LEADER</p>
                                            <p>goofcode@gmail.com</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-4 col-sm-6">
                                <div class="project-item">
                                    <img src="img/developers/heero.png" alt="">
                                    <div class="project-hover">
                                        <div class="inside">
                                            <h5><a href="#">Heero Chung</a></h5>
                                            <p>App client, UCSD Student</p>
                                            <p>hrchung415@gmail.com</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-4 col-sm-6">
                                <div class="project-item">
                                    <img src="img/developers/leo.png" alt="">
                                    <div class="project-hover">
                                        <div class="inside">
                                            <h3><a href="#">Junyoung Park (Leo)</a></h3>
                                            <p>Server, unhealthy</p>
                                            <p>leopark3846@gmail.com</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div> <!-- .projects-holder -->
                    </div>

                <?php require 'common/footer.php' ?>
            </div>
        </div>
    </div>
<?php require 'common/end.php' ?>
