<?php require 'common/begin.php' ?>

    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="fluid-container">
            <div class="content-wrapper">

                <!-- ABOUT -->
                <div class="page-section" id="about">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="widget-title">About This Project</h4>
                        <div class="about-image">
                            <img src="img/8.jpg" alt="about project">
                        </div>
                        <p>This health related monitoring system project shows you the real-time and historical air quality data from various area in the world. Also, you can check your heart rate  </p>
                        <hr>
                    </div>
                </div> <!-- #about -->

                <?php require 'common/footer.php' ?>
            </div>
        </div>
    </div>
<?php require 'common/end.php' ?>
