<?php require 'common/begin.php' ?>
    <!-- CONTENT TOP -->
    <div class="banner-bg" id="top">
        <div class="banner-overlay"></div>
        <div class="welcome-text">
            <h1>Air Quality & Heart-rate Monitoring System</h1>
            <h5>QI IoT 2018 Winter Program - Team D</h5>
        </div>
    </div>

    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="fluid-container">
            <div class="content-wrapper">

                <!-- ABOUT -->
                <div class="page-section" id="about">
                    <div class="row">
                        <div class="col-xs-12">
                            <h4 class="widget-title">About This Project</h4>
                            <div class="about-image">
                                <img src="img/qi_building_edit.jpg" alt="about project">
                            </div>
                            <h2>Is it OK to breathe right now?</h2><br/>
                            <p>
                                Recently, there are a lot of air pollutants(CO, PM2.5, O3, SO2, etc).
                                Also, there are a lot of situations to make air pollutants in outside.
                                The government opens the air pollution data to public, but it can't measure the air that I breathe right now.
                                We started this project that question to measure the air that I breathe right now.
                            </p>
                            <!--<p>This health related monitoring system project shows you the real-time and historical air quality data from various area in the world. Also, you can check your heart rate  </p>-->
                            <hr>
                        </div>
                    </div> <!-- #about -->
                </div>

                <!-- Map intro -->
                <div class="page-section" id="projects">
                <div class="row">
                    <div class="col-xs-12">
                        <h4 class="widget-title">Features of this project</h4>
                        <!--<p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Maecenas et lorem molestie, maximus justo dignissim, cursus nisl. Nullam at ante quis ex pharetra pulvinar quis id dolor. Integer lorem odio, euismod ut sem sit amet, imperdiet condimentum diam.</p>-->
                    </div>
                </div>
                <div class="row projects-holder">
                    <div class="col-xs-12 col-md-4 col-sm-6">
                        <div class="project-item">
                            <img src="img/project-item/1.png" alt="">
                            <div class="project-hover">
                                <div class="inside">
                                    <h5><a href="map">Display real-time AQI on google maps</a></h5>
                                    <!--<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam cursus</p>-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-6">
                        <div class="project-item">
                            <img src="img/project-item/2.png" alt="">
                            <div class="project-hover">
                                <div class="inside">
                                    <h5><a href="charts">Check my historical sensor data. </a></h5>
                                    <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam cursus</p> -->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-6">
                        <div class="project-item">
                            <img src="img/project-item/33.png" alt="">
                            <div class="project-hover">
                                <div class="inside">
                                    <h5><a href="#">Using UDOO Neo to collect faster and stronger sensor data. </a></h5>
                                    <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam cursus.</p> -->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-6">
                        <div class="project-item">
                            <img src="img/project-item/4.png" alt="">
                            <div class="project-hover">
                                <div class="inside">
                                    <h5><a href="#">Make to breathe healthy for our children. </a></h5>
                                    <!-- <p>Quisque mattis sit amet dolor eu scelerisque. Vivamus bibendum massa et nisl tempus commodo.</p> -->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-6">
                        <div class="project-item">
                            <img src="img/project-item/5.png" alt="">
                            <div class="project-hover">
                                <div class="inside">
                                    <h5><a href="#">Avoid the pollutants with realtime data. </a></h5>
                                    <!--<p>Quisque mattis sit amet dolor eu scelerisque. Vivamus bibendum massa et nisl tempus commodo.</p>-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-6">
                        <div class="project-item">
                            <img src="img/6.jpg" alt="">
                            <div class="project-hover">
                                <div class="inside">
                                    <h5><a href="#">Pellentesque porta ligula</a></h5>
                                    <p>Quisque mattis sit amet dolor eu scelerisque. Vivamus bibendum massa et nisl tempus commodo.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- .projects-holder -->
                </div>

                <!-- CONTACT -->
                <!--div class="page-section" id="contact">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="widget-title">PLACE TO TALK WITH ME</h4>
                        <p>Vestibulum ac iaculis erat, in semper dolor. Maecenas et lorem molestie, maximus justo dignissim, cursus nisl. Nullam at ante quis ex pharetra pulvinar quis id dolor. Integer lorem odio, euismod ut sem sit amet, imperdiet condimentum diam.</p>
                    </div>
                </div>
                <div class="row">
                    <form action="#" method="post" class="contact-form">
                        <fieldset class="col-md-4 col-sm-6">
                            <input type="text" id="your-name" placeholder="Your Name...">
                        </fieldset>
                        <fieldset class="col-md-4 col-sm-6">
                            <input type="email" id="email" placeholder="Your Email...">
                        </fieldset>
                        <fieldset class="col-md-4 col-sm-12">
                            <input type="text" id="your-subject" placeholder="Subject...">
                        </fieldset>
                        <fieldset class="col-md-12 col-sm-12">
                            <textarea name="message" id="message" cols="30" rows="6" placeholder="Leave your message..."></textarea>
                        </fieldset>
                        <fieldset class="col-md-12 col-sm-12">
                            <input type="submit" class="button big default" value="Send Message">
                        </fieldset>
                    </form>
                </div>
                </div-->

                <?php require 'common/footer.php' ?>
            </div>
        </div>
    </div>
<?php require 'common/end.php' ?>
