<?php require 'common/begin.php' ?>

    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="fluid-container">
            <div class="content-wrapper">

                <div class="map-container">

                    <div id="air-map"></div>
                    <script>
                        var map;

                        function initMap() {
                            map = new google.maps.Map(document.getElementById('air-map'), {
                                center: { lat:32.8787614, lng:-117.2349534 },
                                zoom: 12,
                                styles:[
                                    {"featureType": "landscape", "stylers": [{"hue": "#FFBB00"}, {"saturation": 43.400000000000006}, { "lightness": 37.599999999999994}, {"gamma": 1}]},
                                    {"featureType": "road.highway", "stylers": [{"hue": "#FFC200"}, {"saturation": -61.8}, {"lightness": 45.599999999999994}, {"gamma": 1}]},
                                    {"featureType": "road.arterial", "stylers": [{"hue": "#FF0300"}, {"saturation": -100}, {"lightness": 51.19999999999999}, {"gamma": 1}]},
                                    {"featureType": "road.local", "stylers": [{"hue": "#FF0300"}, {"saturation": -100}, {"lightness": 52}, {"gamma": 1}]},
                                    {"featureType": "water", "stylers": [{"hue": "#0078FF"}, {"saturation": -13.200000000000003}, {"lightness": 2.4000000000000057}, {"gamma": 1}]},
                                    {"featureType": "poi", "stylers": [{"hue": "#00FF6A"}, {"saturation": -1.0989010989011234}, {"lightness": 11.200000000000017}, {"gamma": 1}]}
                                ]
                            });

                            var zoom = map.getZoom();
                            map.data.setStyle(function(feature) {
                                var concentration = feature.getProperty('radius');
                                return {
                                    title: feature.getProperty('radius'),
                                    icon: getCircle(zoom, concentration)
                                };
                            });

                            google.maps.event.addListener(map, "dragend", function(){
                                clearFeatures();
                                getAirData(map.getBounds());
                            });
                            google.maps.event.addListener(map, "zoom_changed", function(){
                                clearFeatures();
                                getAirData(map.getBounds());
                            });
                            google.maps.event.addListener(map, "projection_changed", function(){
                                clearFeatures();
                                getAirData(map.getBounds());
                            });
                        }
                    </script>
                    <script src="js/kmeans.js"></script>
                    <script src="js/maps.js"></script>
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC94R7siOtY7X9L0P-9pTzQiCn7V2hbCaI&callback=initMap" async defer></script>
                </div>
                <?php require 'common/footer.php' ?>
                <div class="content-wrapper content-text"></div>
            </div>
        </div>
    </div>
<?php require 'common/end.php' ?>

