<?php require 'common/begin.php' ?>

<!-- MAIN CONTENT -->
<div class="main-content">
    <div class="content-wrapper">
        <div class="page-section" id="about">
            <div class="row">
                <div class="user-form">
                    <img id="profile-img" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
                    <p id="profile-name"></p>
                    <form id="signin-form" class="user-auth-form" novalidate="novalidate">
                        <input type="text" id="inputIdentifier" class="form-control" placeholder="Email or User name" required autofocus>
                        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                        <!--div id="remember" class="checkbox">
                            <label>
                                <input type="checkbox" value="remember-me"> Remember me
                            </label>
                        </div-->
                        <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
                    </form><!-- /form -->
                    <br/>
                    <a href="/signup">Sign up</a><br/>
                    <a href="/forgotpw">Forgot the password?</a>

                    <script>
                        $("#signin-form").submit(function(){

                            // valid user input format
                            var identifier = $("#inputIdentifier").val();
                            var password = $("#inputPassword").val();

                            var format_check = isValidSignInFormat(identifier, password);

                            if(format_check.status){

                                var data = {
                                    "identifier":identifier,
                                    "password" : password
                                };
                                $.ajax({
                                    type: "POST",
                                    url: "/api/user/signin",
                                    data: JSON.stringify(data),

                                    success: function(response){

                                        var res = JSON.parse(response);

                                        if(res['status'] === true)
                                            window.location = '/';
                                        else
                                            alert('ERROR: ' + res['code']);
                                    }
                                });
                            }
                            else
                                alert(format_check.message);

                            return false;
                        });
                    </script>
                </div>
            </div>
            <?php require 'common/footer.php' ?>
        </div>
    </div>
</div>
<?php require 'common/end.php' ?>


