---

- name: Copy the nginx yum repository config file
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo

- name: Ensure Nginx installed
  yum: name=nginx state=installed

- name: Copy the nginx main config file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Copy the nginx restrictions file
  template: src=restrictions.conf.j2 dest=/etc/nginx/restrictions.conf

- shell: mkdir -p /etc/nginx/site-available /etc/nginx/site-enabled

- name: Enable the virual host config file
  template: src=vhosts.conf.j2 dest=/etc/nginx/site-available/vhosts.conf

- file:
    state=link force=yes
    src=/etc/nginx/site-available/vhosts.conf
    path=/etc/nginx/site-enabled/vhosts.conf

- service: name=nginx state=restarted enabled=yes