nginx_vhosts: [
  {
    server_name: "slimvc.dev",
    server_aliases: [],
    root: "/var/www/htdocs/slimvc/public/sample"
  }
]
project_base_dir: "/var/www/htdocs/slimvc"
mysql_dump_file: "/var/www/htdocs/slimvc/apps/sample/sql/sample.sql"